import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateReceiptPDF(payment: {
  studentName: string;
  class: string;
  amount: number;
  date: string;
  method: string;
  receiptNo: string;
}) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('RECEIPT', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('SmartSchool Pro', 105, 30, { align: 'center' });
  doc.text('Kampala, Uganda', 105, 36, { align: 'center' });
  doc.text('Tel: 0772 XXX XXX', 105, 42, { align: 'center' });
  
  // Receipt details
  doc.setFontSize(10);
  doc.text(`Receipt No: ${payment.receiptNo}`, 20, 55);
  doc.text(`Date: ${payment.date}`, 20, 62);
  
  // Student info
  doc.setFontSize(12);
  doc.text('Student Details', 20, 75);
  doc.setFontSize(10);
  doc.text(`Name: ${payment.studentName}`, 20, 82);
  doc.text(`Class: ${payment.class}`, 20, 88);
  
  // Payment info
  doc.setFontSize(12);
  doc.text('Payment Details', 20, 100);
  doc.setFontSize(10);
  doc.text(`Amount: UGX ${payment.amount.toLocaleString()}`, 20, 107);
  doc.text(`Method: ${payment.method}`, 20, 113);
  
  // Amount in words
  doc.text(`Amount in Words: ${numberToWords(payment.amount)} shillings only`, 20, 125);
  
  // Footer
  doc.setFontSize(8);
  doc.text('This is a computer-generated receipt.', 105, 270, { align: 'center' });
  doc.text('Thank you for your payment!', 105, 276, { align: 'center' });
  
  return doc;
}

export function generateReportCardPDF(student: {
  name: string;
  class: string;
  admissionNo: string;
  results: { subject: string; score: number; grade: string }[];
  average: number;
  classAverage: number;
  position: number;
  totalStudents: number;
  term: string;
  year: number;
}) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('STUDENT REPORT CARD', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('SmartSchool Pro', 105, 28, { align: 'center' });
  doc.text('P.O. Box 12345, Kampala, Uganda', 105, 34, { align: 'center' });
  
  // Student info box
  doc.rect(15, 40, 180, 20);
  doc.setFontSize(10);
  doc.text(`Name: ${student.name}`, 20, 48);
  doc.text(`Admission No: ${student.admissionNo}`, 20, 54);
  doc.text(`Class: ${student.class}`, 120, 48);
  doc.text(`Term: ${student.term} ${student.year}`, 120, 54);
  
  // Results table
  const tableData = student.results.map(r => [r.subject, r.score.toString(), r.grade]);
  tableData.push(['', '', '']);
  tableData.push(['TOTAL', student.results.reduce((sum, r) => sum + r.score, 0).toString(), '']);
  
  autoTable(doc, {
    startY: 65,
    head: [['Subject', 'Score', 'Grade']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] },
    styles: { halign: 'center' },
    columnStyles: { 0: { halign: 'left' } },
  });
  
  // Summary
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(10);
  doc.text(`Class Average: ${student.classAverage}%`, 20, finalY);
  doc.text(`Overall Average: ${student.average}%`, 20, finalY + 6);
  doc.text(`Position: ${student.position} of ${student.totalStudents}`, 20, finalY + 12);
  
  // Signature boxes
  doc.rect(20, finalY + 25, 60, 25);
  doc.rect(120, finalY + 25, 60, 25);
  doc.text('Class Teacher', 50, finalY + 40, { align: 'center' });
  doc.text('Headteacher', 150, finalY + 40, { align: 'center' });
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by SmartSchool Pro', 105, 285, { align: 'center' });
  
  return doc;
}

function numberToWords(num: number): string {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 
    'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  
  if (num === 0) return 'Zero';
  if (num < 20) return ones[num];
  if (num < 100) return tens[Math.floor(num / 10)] + (num % 10 ? ' ' + ones[num % 10] : '');
  if (num < 1000) return ones[Math.floor(num / 100)] + ' Hundred' + (num % 100 ? ' ' + numberToWords(num % 100) : '');
  if (num < 1000000) return numberToWords(Math.floor(num / 1000)) + ' Thousand' + (num % 1000 ? ' ' + numberToWords(num % 1000) : '');
  return numberToWords(Math.floor(num / 1000000)) + ' Million' + (num % 1000000 ? ' ' + numberToWords(num % 1000000) : '');
}